name: Build and Upload APK

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Change to project directory
        working-directory: Hello_World
        run: pwd

      - name: Verify project files
        working-directory: Hello_World
        run: ls -la

      - name: Make gradlew executable
        working-directory: Hello_World
        run: chmod +x gradlew

      - name: Build APK
        working-directory: Hello_World
        run: ./gradlew assembleRelease

      # Install google-drive-upload globally and add to PATH
      - name: Install google-drive-upload CLI
        run: |
          npm install -g google-drive-upload
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      # Debug PATH after adding npm global bin
      - name: Debug PATH variable
        run: echo $PATH

      # Upload APK in a separate step so PATH includes npm global bin
      - name: Upload APK to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          google-drive-upload Hello_World/app/build/outputs/apk/release/app-release.apk 1erknlEj6gPnwnJJtcVsC0KC0a8vmZT8I
