name: Build and Upload APK

on:
  push:
    branches:
      - main # Specify the branch to trigger the workflow

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Update according to your project requirements
          distribution: 'temurin'
          cache: gradle

      # Step 3: Navigate to Hello_World directory
      - name: Change to project directory
        working-directory: Hello_World # Set working directory to Hello_World
        run: pwd  # Print working directory for debugging

      # Step 4: List directory contents
      - name: List directory contents
        working-directory: Hello_World
        run: ls -la  # Ensure all necessary files are accessible

      # Step 5: Grant execute permissions to gradlew
      - name: Grant execute permissions for gradlew
        working-directory: Hello_World
        run: chmod +x gradlew

      # Step 6: Build APK using the Gradle wrapper
      - name: Build APK
        working-directory: Hello_World
        run: ./gradlew assembleRelease

      # Step 7: Upload APK to Google Drive
      - name: Upload to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          npm install -g google-drive-upload
          google-drive-upload Hello_World/app/build/outputs/apk/release/app-release.apk 1erknlEj6gPnwnJJtcVsC0KC0a8vmZT8I # Replace with your actual Folder ID
