name: Build and Upload APK

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Specify your JDK version
          distribution: 'temurin'
          cache: gradle

      # Step 3: Navigate to the project directory
      - name: Change to project directory
        working-directory: Hello_World
        run: pwd  # Debug: Show the working directory

      # Step 4: Verify directory contents
      - name: List project directory contents
        working-directory: Hello_World
        run: ls -la  # Debug: Check for project files like gradlew

      # Step 5: Grant execute permissions to gradlew
      - name: Grant permissions to gradlew
        working-directory: Hello_World
        run: chmod +x gradlew

      # Step 6: Build the APK
      - name: Build APK
        working-directory: Hello_World
        run: ./gradlew assembleRelease

      # Step 7: Install google-drive-upload and update PATH
      - name: Install google-drive-upload and update PATH
        run: |
          npm install -g google-drive-upload
          # Add npm binary path to PATH securely
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      # Step 8: Upload APK to Google Drive
      - name: Upload APK to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Use GitHub Secrets for credentials
        run: |
          google-drive-upload \
          Hello_World/app/build/outputs/apk/release/app-release.apk \
          1erknlEj6gPnwnJJtcVsC0KC0a8vmZT8I  # Replace with your Google Drive folder ID
