name: Build and Upload APK

on:
  push:
    branches:
      - main # Specify the branch to trigger the workflow

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Update according to your project requirements
          distribution: 'temurin'
          cache: gradle

      # Step 3: Grant execute permissions to the Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x Hello_World/gradlew

      # Step 4: Build APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease

      # Step 5: Upload APK to Google Drive
      - name: Upload to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          npm install -g google-drive-upload
          google-drive-upload ./app/build/outputs/apk/release/app-release.apk <Your-Google-Drive-FolderID> # Replace with your actual Folder ID
