name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        working-directory: Hello_World
        run: chmod +x gradlew

      - name: Build APK
        working-directory: Hello_World
        run: ./gradlew assembleRelease

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload APK to Google Drive Run
        run: |
          rclone copy Hello_World/app/build/outputs/apk/release/app-release.apk CI_CD:MyApkBackups/
