name: Build and Upload APK

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Specify required JDK version
          distribution: 'temurin'
          cache: gradle

      # Step 3: Navigate to the project directory
      - name: Change to project directory
        working-directory: Hello_World
        run: pwd  # Debugging: Check current working directory
      
      # Step 4: Display project directory contents
      - name: Verify project files
        working-directory: Hello_World
        run: ls -la  # Sanity check for project files (like gradlew)

      # Step 5: Grant execute permissions for Gradle wrapper
      - name: Make gradlew executable
        working-directory: Hello_World
        run: chmod +x gradlew

      # Step 6: Build the APK
      - name: Build APK
        working-directory: Hello_World
        run: ./gradlew assembleRelease

      # Step 7: Install google-drive-upload globally
      - name: Install google-drive-upload CLI
        run: |
          npm install -g google-drive-upload
          echo "Adding npm global path to PATH"
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
          echo "::debug::CLI installed, validating installation..."
          google-drive-upload --version || echo "Installation validation failed."

      # Step 8: Debug PATH Variable
      - name: Debug PATH variable
        run: echo PATH=$PATH

      # Step 9: Upload APK to Google Drive
      - name: Upload APK to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          google-drive-upload \
          Hello_World/app/build/outputs/apk/release/app-release.apk \
          1erknlEj6gPnwnJJtcVsC0KC0a8vmZT8I
